# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: آی ترفند
email: mhkarami97@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  آی ترفند
twitter_username: mhkarami97
github_username: mhkarami97
minimal_mistakes_skin: air
search: true
og_image: /assets/images/favicon.png
# teaser: /assets/images/favicon.png
logo: /assets/images/favicon.png

locale: "fa-IR"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 25 # amount of posts to show
paginate_path: /page:num/
timezone: IR

lang: fa
dir: rtl
direction: rtl

url: https://tarfand.mhkarami97.ir

baseurl: "/"

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
#comments:
#   provider: "giscus"
   
repository: "MHKarami97/tarfand"

comments:
  provider: ""
  giscus:
    repo_id              : "MDEwOlJlcG9zaXRvcnkzMjE5OTM3NDM="
    category_name        : "General"
    category_id          : "DIC_kwDOEzE8D84B-PIL"
    discussion_term      : "pathname"
    reactions_enabled    : "1"
    theme                : "light"
    crossorigin          : "anonymous" 

#utterances:
#  repo: "MHKarami97/tarfand"
#  issue-term: "pathname"
#  label: "Comments"
#  theme: "github-light"
  
#giscus:
#  repo: "MHKarami97/tarfand"
#  repo-id: "MDEwOlJlcG9zaXRvcnkzMjE5OTM3NDM="
#  category: "General"
#  category-id: "DIC_kwDOEzE8D84B-PIL"
#  mapping: "pathname"
#  reaction-enabled: "1"
#  theme: "light"
#  crossorigin: "anonymous"  
  
#   disqus:
#     shortname: "mhkarami97"
# disqus: "mhkarami97"  

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: "G-2KGKGYQR60"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-2KGKGYQR60"
    anonymize_ip: false # default
    
google_site_verification: "BVwx9je8Sv6HbUTtZ4yJrPvJLZzE0wEsPS2VJHQzOKo"    
  
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name   : "محمد حسین کرمی"
  avatar : "/assets/images/my.jpg"
  bio    : "آی ترفند"
  links:
    - label: "وبسایت"
      icon: "fas fa-fw fa-link"
      url: "https://mhkarami97.ir"
    - label: "آپارات"
      icon: "fas fa-fw fa-link"
      url: "https://aparat.com/mhkarami97"

footer:
  links:
    - label: "وبسایت"
      icon: "fas fa-fw fa-link"
      url: "https://mhkarami97.ir"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      lang: fa
      direction: rtl
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      lang: fa
      direction: rtl

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
